os: linux
dist: xenial  # ubuntu 16.04

language: python

branches:
  only:
    - master
    - /\d*\.\d*\.\d*/

env:
  global:
    - COVERAGE=false
    - secure: "FYpTesGG7xkAauux8kxImmPC8/0osoUXFimhosZOQyi8qc91qURyqhD7L9H/Xmokr+z9cIGUkp/tg6yHiipTB+z65+2I8nNt+zMi/n835XIVr83dbSyQysc8jK1jdUZdwnt83v8FrgveK9YAaylu0dU2c/LDQmsO7FUg06HZS+1QZOUdpLWFknHusA5TdhvzZfmmjwbJCde+jQhhpzkQ/YrWCMbW2WgAPvN2ofEL5k3QlXKzgCe4iayQYHwtpHYejQVq7KM+PiyptuekXZNWvyvMk8a/kqs7XXo09V/jsdg32eP3q2cwVSipfVKhLobxvtL1iY5bEGbA24cdHwvjsr4tKcRsXSAglhkDUuIsGPQJedG6tB3fuA6egvQE5O/ZX8ORhH7wu5EkyzOIBdqPNk7SpshckhXv/zuNTdVjojGmh0PgUrfmTu4HXEyr/r5E7TvwljINncsR1+Xypgdj3X9QDmWfjduyEFC2plgEQHpui7tVOPR2wpPrsggZsrzfdNRsJ6ZpUAhXuAgDCt2iISkNVjDg7gBLf08QHgafjfhFW6Xh0Ci01akdK7k5GCC7zqnl3rON1yBEmXF3t57yqTNPEyYepxJYjQCPZYu/2z+hxs6Edo0aRmUaKTDjZXtK2XgX2Fk01ImZL4dREwI2Yu+/y+JyRBjiajp7mYXC7Pg="
    - secure: "AOoJA80phQcMXvoGxXrBfDHN3aSgunplTDOYrf0coRJRJ+Mk8bdsWj8OuBwziWvTdWfc0B2uZg/gMDR4Qe4Wc96uH5HJrxbou3/GS9Gr2XSSGy00SjCuTCKkgo47tfFgtPnabZ/QIP3TG67DuESxwFE3a31VFCCFMJy33MFzSEiBuDzNwuZnueuYRp/vWX1l7eaRFsPVq+O0SKkH8KGLGM3b9/lo2Xci1O/M951CVcK0fh8hirmPjGavWGlc8MF5skMg2HqpgEY9mAn6+CidWNqvTvEFmnMARnz+0iwAq/iuEFbXIoSbYZi7QafEZWau5NEUlRrXywyF+ZivjcvQ54FQgmMnHTvM2gM0z95bEpTG8dSZzfRHhIEzu9GlCN/7VwF+ZnmHcZaqftNPAXEx5iFT/6N3yoFRPzrp+JSObAqppLW+QIFIAvpeeoEaOtIRaZJtk1uvgQ7tiz69Y0ZfJyYBgGj09OiQLQ/hCxmV9OlJgRqUwXobk3vAV4en305eJ8U5ChqmnjfObmUfOjVChi/pv/AVwZT9dqsfupTtdMdk/tQHehnp6npfLxCGSCAKyqm5rib5AopuOTER4wn4iqXUEv7ERL7lRG0UI79zqcrYc5yV0orNleS5fQepqeEhoxUQ3ga9A8bbJwzOtmlJhVdkZnP3kUXAnGlfQNbaA80="

matrix:
  include:
    - python: 3.6
    - python: 3.7
      env:
        - COVERAGE=true

install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes true
  - conda config --prepend channels conda-forge
  - conda config --append channels bashtage
  - conda config --set anaconda_upload yes
  - conda update --all --quiet
  - conda create -n build_env python=${TRAVIS_PYTHON_VERSION} copulae coveralls nlopt numpy pandas pytest pytest-cov scipy statsmodels xlrd
  - source activate build_env

script:
  - make test

after_success:
  - echo "Test succeeded"
  - |
    if [[ "$COVERAGE" = true ]]; then
      echo "Uploading coverage report"
      coveralls;
    fi
  - |
    if [[ ! -z "$TRAVIS_TAG" ]]; then
      echo "Building and uploading package to anaconda"
      conda install anaconda-client conda-build conda-verify
      anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_PASSWORD
      conda build --output-folder dists conda.recipe
    fi

deploy:
  - provider: pypi
    user: DannieBee
    password:
      secure: PPzw/f41pAwZHnUBkIlqPbvzWEeiUftBNa5EpQu117dLVE4Zb+C4QpjrR3wJLYp7O3ZDUx45TW3rBO5qDABtD5ufDcHbrllGeByT1BBPzZBKl4thXmB58CjvFwJFjO/zIddMIKSQe/Za9BCKD6nkjLiSvEx6pRMREH2255h4KH/pTuLXiD9pHgCwJA0mNtUYB3rHdUPOPjpWSP3niZSyoUHCibWB+9Y/u0J9qgVGPLE9kydA1aboJWUWJ/7gBaNoyhvSdcWAt1JPQCLMNiXccBLeq15ajt141wMEYR1k7JWBzgkt4S5wDSloGjaTn49ir545Ptp95OG4XK+ynw3EkGSpymihYCDfemvjG/KrdS91mfcxQhGXXyVmyNBZrXMmoJlEHlFGHiuhavzOhWScv7qiqIK0YJ0U4+fut9RJ1fi8niB+KsI51UfPsE5KDv/yioKrGTVkdxJKq89WF21FLM8npyc/v3+29/g9LIOUo9zVHOno77FeVGaJtaCFh8Gt7Kcn9VM4ee4CMV7ByFfYj6cEecWJxZaPdTfKzVWUhFoiwkuFu86BcD27Zn9QKm9odLci/kCYxHcvsNDwqbH7q3auro5QJaR9iNUOj1eKzn8gfc1pn/30RB1S15O70rWmJ90vgJCpdlYij91Y8PsN9QPnyFd50H6SOgaSl5pVAI8=
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
